paths:
  static: ''
  uploads: uploads
  pages:
  '*.html':
    editable: true
timezone: Asia/Calcutta
markdown:
  engine: commonmark
  options: {}
collections_config:
  commercial:
    path: commercial
    icon: camera
