collections_config:
  commercial:
    path: commercial
    icon: camera
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Etc/UTC
static_site_generator: none
build:
  command: echo "Serving static files directly"
output_path: /
