paths:
  static: ''       # root of your repo where HTML files are located
  uploads: uploads # folder for uploaded media
  pages:
    '*.html':
      editable: true

timezone: Asia/Calcutta

markdown:
  engine: commonmark
  options: {}
